from app import db, Belts

belt1 = Belts(belt_name='Orange - One White Stripe')
belt2 = Belts(belt_name='Orange')
belt3 = Belts(belt_name='Yellow')
belt4 = Belts(belt_name='Green')
belt5 = Belts(belt_name='Purple')
belt6 = Belts(belt_name='Blue')
belt7 = Belts(belt_name='Brown - One White Stripe')
belt8 = Belts(belt_name='Brown - Two White Stripes')
belt9 = Belts(belt_name='Brown')
belt10 = Belts(belt_name='1st Dan')
belt11 = Belts(belt_name='2nd Dan')
belt12 = Belts(belt_name='3rd Dan')
belt13 = Belts(belt_name='4th Dan')
belt14 = Belts(belt_name='5th Dan')
belt15 = Belts(belt_name='6th Dan')
belt16 = Belts(belt_name='7th Dan')
belt17 = Belts(belt_name='8th Dan')
belt18 = Belts(belt_name='9th Dan')
belt19 = Belts(belt_name='10th Dan')

db.session.add(belt1)
db.session.add(belt2)
db.session.add(belt3)
db.session.add(belt4)
db.session.add(belt5)
db.session.add(belt6)
db.session.add(belt7)
db.session.add(belt8)
db.session.add(belt9)
db.session.add(belt10)
db.session.add(belt11)
db.session.add(belt12)
db.session.add(belt13)
db.session.add(belt14)
db.session.add(belt15)
db.session.add(belt16)
db.session.add(belt17)
db.session.add(belt18)
db.session.add(belt19)




#db.session.commit()
